import {
  getGenerateAppSpecUrl,
  isAiGenerationEnabled,
} from '../firebase/firebaseClient'
import { normalizeAppSpec } from '../storage/appForgeStore'
import type { AppSpec, GeneratedAppDraft } from '../types/appSpec'
import { appSpecModelSummary } from './appSpecModelSummary'

interface GenerateAppSpecCallableRequest {
  prompt: string
  existingAppSpecModelSummary?: string
}

interface GenerateAppSpecCallableResponse {
  appSpec: AppSpec
  warnings: string[]
}

interface CallableHttpResponse {
  data?: GenerateAppSpecCallableResponse
  error?: {
    details?: unknown
    message?: string
    status?: string
  }
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value)

const warningListFrom = (value: unknown) =>
  Array.isArray(value)
    ? value
        .filter((warning): warning is string => typeof warning === 'string')
        .map((warning) => warning.trim())
        .filter(Boolean)
    : []

const callableHttpResponseFrom = (value: unknown): CallableHttpResponse => {
  if (!isRecord(value)) {
    return {}
  }

  return {
    data: isRecord(value.data)
      ? (value.data as unknown as GenerateAppSpecCallableResponse)
      : undefined,
    error: isRecord(value.error)
      ? {
          details: value.error.details,
          message:
            typeof value.error.message === 'string'
              ? value.error.message
              : undefined,
          status:
            typeof value.error.status === 'string'
              ? value.error.status
              : undefined,
        }
      : undefined,
  }
}

const messageFromCallableError = (payload: CallableHttpResponse) => {
  const message = payload.error?.message?.trim()
  const status = payload.error?.status?.trim()
  const details = payload.error?.details

  if (
    isRecord(details) &&
    'message' in details &&
    typeof details.message === 'string'
  ) {
    return message ? `${message}: ${details.message}` : details.message
  }

  if (message && status) {
    return `${status}: ${message}`
  }

  return message || 'AI generation failed. You can use the local mock generator instead.'
}

export const generateAppSpecWithAI = async (
  prompt: string,
): Promise<GeneratedAppDraft> => {
  if (!isAiGenerationEnabled()) {
    throw new Error(
      'AI generation is disabled by VITE_ENABLE_AI_GENERATION. Set it to true only when you intentionally want to spend OpenAI credits.',
    )
  }

  const endpoint = getGenerateAppSpecUrl()

  if (!endpoint) {
    throw new Error(
      'Firebase is not configured for this build. Add Vite Firebase environment variables to enable AI generation.',
    )
  }

  const requestBody: GenerateAppSpecCallableRequest = {
    prompt,
    existingAppSpecModelSummary: appSpecModelSummary,
  }

  const response = await fetch(endpoint, {
    body: JSON.stringify({ data: requestBody }),
    headers: {
      'Content-Type': 'application/json',
    },
    method: 'POST',
  })

  const payload = callableHttpResponseFrom(await response.json().catch(() => ({})))

  if (!response.ok || payload.error) {
    throw new Error(messageFromCallableError(payload))
  }

  if (!payload.data) {
    throw new Error('AI generation response did not include app data.')
  }

  const appSpec = normalizeAppSpec(payload.data.appSpec)

  if (!appSpec) {
    throw new Error('AI returned an AppSpec that AppForge could not render safely.')
  }

  const warnings = warningListFrom(payload.data.warnings)

  return {
    prompt,
    appSpec,
    assumptions: [
      'Generated by the Firebase generateAppSpec function.',
      'The backend validated and sanitized the AppSpec before returning it.',
      ...warnings,
    ],
    source: 'ai',
    warnings,
  }
}
