import { httpsCallable } from 'firebase/functions'
import {
  getAppForgeFunctions,
  isAiGenerationEnabled,
} from '../firebase/firebaseClient'
import { normalizeAppSpec } from '../storage/appForgeStore'
import type { AppSpec, GeneratedAppDraft } from '../types/appSpec'
import { appSpecModelSummary } from './appSpecModelSummary'

interface GenerateAppSpecCallableRequest {
  prompt: string
  existingAppSpecModelSummary?: string
}

interface GenerateAppSpecCallableResponse {
  appSpec: AppSpec
  warnings: string[]
}

const warningListFrom = (value: unknown) =>
  Array.isArray(value)
    ? value
        .filter((warning): warning is string => typeof warning === 'string')
        .map((warning) => warning.trim())
        .filter(Boolean)
    : []

const callableErrorMessage = (error: unknown) => {
  if (!(error instanceof Error)) {
    return 'AI generation failed. You can use the local mock generator instead.'
  }

  const details =
    'customData' in error &&
    typeof error.customData === 'object' &&
    error.customData !== null &&
    'serverResponse' in error.customData &&
    typeof error.customData.serverResponse === 'object' &&
    error.customData.serverResponse !== null &&
    'error' in error.customData.serverResponse &&
    typeof error.customData.serverResponse.error === 'object' &&
    error.customData.serverResponse.error !== null &&
    'details' in error.customData.serverResponse.error
      ? error.customData.serverResponse.error.details
      : undefined

  if (
    details &&
    typeof details === 'object' &&
    'message' in details &&
    typeof details.message === 'string'
  ) {
    return `${error.message}: ${details.message}`
  }

  return error.message
}

export const generateAppSpecWithAI = async (
  prompt: string,
): Promise<GeneratedAppDraft> => {
  if (!isAiGenerationEnabled()) {
    throw new Error(
      'AI generation is disabled by VITE_ENABLE_AI_GENERATION. Set it to true only when you intentionally want to spend OpenAI credits.',
    )
  }

  const functions = getAppForgeFunctions()

  if (!functions) {
    throw new Error(
      'Firebase is not configured for this build. Add Vite Firebase environment variables to enable AI generation.',
    )
  }

  const callable = httpsCallable<
    GenerateAppSpecCallableRequest,
    GenerateAppSpecCallableResponse
  >(functions, 'generateAppSpec')

  let result

  try {
    result = await callable({
      prompt,
      existingAppSpecModelSummary: appSpecModelSummary,
    })
  } catch (error) {
    throw new Error(callableErrorMessage(error), { cause: error })
  }

  const appSpec = normalizeAppSpec(result.data.appSpec)

  if (!appSpec) {
    throw new Error('AI returned an AppSpec that AppForge could not render safely.')
  }

  const warnings = warningListFrom(result.data.warnings)

  return {
    prompt,
    appSpec,
    assumptions: [
      'Generated by the Firebase generateAppSpec callable function.',
      'The backend validated and sanitized the AppSpec before returning it.',
      ...warnings,
    ],
    source: 'ai',
    warnings,
  }
}
