import { httpsCallable } from 'firebase/functions'
import { getAppForgeFunctions } from '../firebase/firebaseClient'
import { normalizeAppSpec } from '../storage/appForgeStore'
import type { AppSpec, GeneratedAppDraft } from '../types/appSpec'
import { appSpecModelSummary } from './appSpecModelSummary'

interface GenerateAppSpecCallableRequest {
  prompt: string
  existingAppSpecModelSummary?: string
}

interface GenerateAppSpecCallableResponse {
  appSpec: AppSpec
  warnings: string[]
}

const warningListFrom = (value: unknown) =>
  Array.isArray(value)
    ? value
        .filter((warning): warning is string => typeof warning === 'string')
        .map((warning) => warning.trim())
        .filter(Boolean)
    : []

export const generateAppSpecWithAI = async (
  prompt: string,
): Promise<GeneratedAppDraft> => {
  const functions = getAppForgeFunctions()

  if (!functions) {
    throw new Error(
      'Firebase is not configured for this build. Add Vite Firebase environment variables to enable AI generation.',
    )
  }

  const callable = httpsCallable<
    GenerateAppSpecCallableRequest,
    GenerateAppSpecCallableResponse
  >(functions, 'generateAppSpec')

  const result = await callable({
    prompt,
    existingAppSpecModelSummary: appSpecModelSummary,
  })
  const appSpec = normalizeAppSpec(result.data.appSpec)

  if (!appSpec) {
    throw new Error('AI returned an AppSpec that AppForge could not render safely.')
  }

  const warnings = warningListFrom(result.data.warnings)

  return {
    prompt,
    appSpec,
    assumptions: [
      'Generated by the Firebase generateAppSpec callable function.',
      'The backend validated and sanitized the AppSpec before returning it.',
      ...warnings,
    ],
    source: 'ai',
    warnings,
  }
}
